var EditorConstants = {
  ActionTypes: {
    CREATE_SCRIPT: 'CREATE_SCRIPT',
    SELECT_SCRIPT: 'SELECT_SCRIPT',
    UPDATE_UI_VISIBILITIES: 'UPDATE_UI_VISIBILITIES',

    FETCH_EXAMPLELIST_ATTEMPT: 'FETCH_EXAMPLELIST_ATTEMPT',
    FETCH_EXAMPLELIST_SUCCESS: 'FETCH_EXAMPLELIST_SUCCESS',
    FETCH_EXAMPLELIST_FAIL: 'FETCH_EXAMPLELIST_FAIL',

    FETCH_EXAMPLE_ATTEMPT: 'FETCH_EXAMPLE_ATTEMPT',
    FETCH_EXAMPLE_SUCCESS: 'FETCH_EXAMPLE_SUCCESS',
    FETCH_EXAMPLE_FAIL: 'FETCH_EXAMPLE_FAIL'
  }
};

module.exports = exports = EditorConstants;
